# Generated by Django 6.1 on 2026-09-21 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('referral_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('referral_count', models.IntegerField(default=0)),
                ('marketing_emails', models.BooleanField(default=True)),
                ('product_updates', models.BooleanField(default=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('team', 'Team')], default='free', max_length=10)),
                ('plan_started_at', models.DateTimeField(blank=True, null=True)),
                ('plan_renews_at', models.DateTimeField(blank=True, null=True)),
                ('has_payment_method', models.BooleanField(default=False)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
